CREATE TABLE "public"."user" (
  "id"         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "created_at" timestamp with time zone NOT NULL DEFAULT now(),
  "email"      text                     NOT NULL,
  CONSTRAINT "user_email_key" UNIQUE (email),
  CONSTRAINT "user_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."user"
  ENABLE ROW LEVEL SECURITY;

COMMENT ON TABLE "public"."user" IS 'Table that stores user';

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."user" TO "anon", "authenticated", "postgres", "service_role";
